### ISSUE TITLE
POUTINE error with input phenotype sample names appears bogus

### ISSUE THREAD

**Issue by marade** [Peter-Two-Point-O/POUTINE#4]
I get this error when running POUTINE:

Error: the following sample names from the input phenotype file do not match with sample names in either/both the input genotype and/or tree files:
samp1
samp2
...

But the sample names are indeed present in the input Fasta and Newick files.

**Comment by Peter-Two-Point-O** [comment]
Just to ask a basic question, do samples names (e.g. "samp1", "samp2") match exactly between all input files (fasta, newick, and pheno files)?  If they do, you can feel free to send me your input files and I'll take a look at it.  Thanks for reporting this.

**Comment by marade** [comment]
It looks like this was a problem on my end, where one of the input files was getting swapped for an old version right before the run, so I reckon we can close the issue. Thanks for your hard work on this software.

**Comment by Peter-Two-Point-O** [comment]
You're absolutely welcome.  I'm glad you got the issue resolved.  I'm also glad I coded that check for sample names :). Please do reach out again if you need us to take a look at anything else or would simply like comments on applying it to your dataset.  We'd be happy to engage.

**Comment by marade** [comment]
Much appreciated Peter.
