### ISSUE TITLE
Issue with names of ancestral reconstruction files

### ISSUE THREAD

**Issue by OGrondin** [Peter-Two-Point-O/POUTINE#5]
Hi, first of all, **thank you for developing this tool** !

I am currently having trouble running it, probably when POUTINE calls the "nexus_to_newick()" function, here is the error message I encounter :
![image](https://user-images.githubusercontent.com/50087334/173558005-ab0ca203-05f7-40d4-83cc-f5aff87db249.png)

I have investigated this and it comes from the "ancestral_reconstruction" files being named "ancestral_sequences{}.fasta" and "annotated_tree{}.nexus" instead of the expected ""ancestral_sequences.fasta" and "annotated_tree.nexus".

The files are otherwise fine and completely identical (same md5-sum hash) to a previous run with the same data.
There is a "branch_mutations.txt" file and no "ancestral_tree.newick" file in the folder.

Good (top) and bad (bottom) "ancestral_reconstruction" folders to illustrate the issue :

![image](https://user-images.githubusercontent.com/50087334/173574081-aeac460c-46c9-4699-b3e4-22c2e8d84184.png)

![image](https://user-images.githubusercontent.com/50087334/173574197-9b12c147-fc9e-4a43-a45c-2773d04bb8db.png)

Here is the command I am running for your information :

```
./poutine.sh --fasta /2022_Bact-GWAS_NiGo/data/50n_run1/POUTINE/POUTINE_friendly.pseudo.mfa \
        --phenos /2022_Bact-GWAS_NiGo/data/50n_run1/pheno/pheno_2_col_noheader.POUTINE \
        --tree /2022_Bact-GWAS_NiGo/data/50n_run1/pruned_tree_run1.treefile \
        --map /2022_Bact-GWAS_NiGo/data/50n_run1/POUTINE/Pos_Physiques.pseudo.map \
        --out-dir /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test \
        --force-overwrite
```
I also tried running it in a one liner without using "\\" to continue lines with the same results...

Here is the log of a faulty run :

```
poutine 1.0.0 session start time: 2022-June-14 Tuesday 10h:16m:06s GMT

Command line options used:
genotype file: /2022_Bact-GWAS_NiGo/data/50n_run1/POUTINE/POUTINE_friendly.pseudo.mfa
phenotype file: /2022_Bact-GWAS_NiGo/data/50n_run1/pheno/pheno_2_col_noheader.POUTINE
tree file: /2022_Bact-GWAS_NiGo/data/50n_run1/pruned_tree_run1.treefile
plink map file: /2022_Bact-GWAS_NiGo/data/50n_run1/POUTINE/Pos_Physiques.pseudo.map
# replicates: 100000
min # homoplasic mutations required at each segregating site: 1
Is --use-precomputed-anc-recon in use?: false
# threads used: 8
ouput directory: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test
     log file: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/poutine_session_2022-06-14_10h-16m-06s.log
     results file (sorted by physical position): /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/poutine_session_2022-06-14_10h-16m-06s.out
     results file by major allele (sorted by maxT pvalue): /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/poutine_session_2022-06-14_10h-16m-06s.out.sorted_by_a1_maxT
     results file by minor allele (sorted by maxT pvalue): /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/poutine_session_2022-06-14_10h-16m-06s.out.sorted_by_a2_maxT
ancestral reconstruction output directory: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/ancestral_reconstruction_2022-06-14_10h-16m-06s
     ancestral genotypes file: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/ancestral_reconstruction_2022-06-14_10h-16m-06s/ancestral_sequences.fasta
     ancestral tree file: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/ancestral_reconstruction_2022-06-14_10h-16m-06s/ancestral_tree.newick
Is --timestamp option in use?: false
Is --force-overwrite option in use?: true
DEBUG MODE: false

treetime command: [treetime, ancestral, --aln, /2022_Bact-GWAS_NiGo/data/50n_run1/POUTINE/POUTINE_friendly.pseudo.mfa, --tree, /2022_Bact-GWAS_NiGo/data/50n_run1/pruned_tree_run1.treefile, --outdir, /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/ancestral_reconstruction_2022-06-14_10h-16m-06s, --gtr, infer]
java.io.FileNotFoundException: /2022_Bact-GWAS_NiGo/output/output_POUTINE_Test/ancestral_reconstruction_2022-06-14_10h-16m-06s/annotated_tree.nexus (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at Homoplasy_Counter.nexus_to_newick(Homoplasy_Counter.java:878)
	at Homoplasy_Counter.call(Homoplasy_Counter.java:260)
	at Homoplasy_Counter.call(Homoplasy_Counter.java:51)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at Homoplasy_Counter.main(Homoplasy_Counter.java:224)
```

I am aware of the "--use-precomputed-anc-recon" tag but would rather not use it if possible.

Would you happen to know how the file names might have gotten these extra curly braces in them ?

Kindly yours,
Nicolas

**Comment by Peter-Two-Point-O** [comment]
Hi Nicolas,

Thanks for the thorough description, it's much appreciated.  Yes, the problem you describe is known.  Unfortunately, in the latest update to Treetime, they changed their hard-coded output filenames and added the braces you mentioned above.  I'll need to make a small patch for this and do it in a way that's immune to future Treetime output filename changes (coming soon!).  In the meantime, if you don't want to use the "--use-precomputed-anc-recon" option with the braces in the Treetime output filenames manually removed (this would circumvent the problem), you can run a slightly older version of Treetime that doesn't added the curly braces to the output filenames.  Please reach out to me if you have other questions or want a deeper discussion of using POUTINE.  Would be happy to help.

**Comment by OGrondin** [comment]
Hi Peter,

Thanks a lot for your quick and useful response !
A colleague and I have tried implementing a dirty fix by adding two blocks to replace the two file names before calling them in your "Homoplasy_Counter.java" script but we don't know much about Java and its compiling, so we couldn't test it out.
You can find our fork with modified "Homoplasy_Counter.java" script [here](https://github.com/A-BN/POUTINE), with no guarantee.

I reversed to the v0.8.6 version of treetime (with `git checkout 7b1ab62` and `pip install .` in the folder where treetime is cloned) as it doesn't have the problematic "tree_suffix" which is responsible for the curly braces in filenames. 
As you can see it worked like a charm:
![image](https://user-images.githubusercontent.com/50087334/173819666-894323bb-8893-4138-a0db-2b4fcfa2723a.png)

Since no issue on treetime's repo talks about this problems since the latest release, I might open one that links to this issue.

Thanks again for your time and for making yourself available,
Cheers,
Nicolas

**Comment by Peter-Two-Point-O** [comment]
Hi Nicolas,

I'm pleased to hear that POUTINE is now working for you and your team.  Again, I'll have a patch for this Treetime issue soon.  Please don't hesitate to reach out if you desire further discussion on microbial GWAS.
