### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by NiloofarVaghefi** [Peter-Two-Point-O/POUTINE#6]
Hi there
I have installed all requirements and added to PATH. when I run 
./poutine.sh --help
it does not print out anything and it does not tell me what is wrong. A window opens and closes very quickly and I cannot see what the problem is. Probably have not installed it properly, but not sure what is wrong. Just wondering if this is something you can help with?
Thanks

**Comment by Peter-Two-Point-O** [comment]
Hi Niloofar,

Thanks for sending us the question.  I received your email outside of Github issues, so I'll respond directly there.  It sounds like a specific situation on your local end as there is no code in POUTINE to open up a separate window from your Unix terminal.  Check your email for my response!

Warmly,
Peter
